### ISSUE TITLE
Incomplete transactional events not being invoked after restarting application

### ISSUE THREAD

**Issue by oalbader** [odrotbohm/moduliths#201]
Hi, I use same tests in moduliths-events-tests but I replaced H2 db with postgres to verify that incomplete transactional events being invoked after restarting application, but I noticed that it's not invoked and it's being marked as completed.

listener.onApplicationEvent(publication.getApplicationEvent()); // nothing happen here
registry.get().markCompleted(publication); // invoked successfully

do I miss something?

**Comment by oalbader** [comment]
debuggin listener.onApplicationEvent(publication.getApplicationEvent()); shows this log => 
No transaction is active - skipping org.springframework.context.PayloadApplicationEvent[source=org.moduliths.events.jpa.JpaEventPublicationRegistry$JpaEventPublicationAdapter@fe22af34]

**Comment by oalbader** [comment]
I put `fallbackExecution = true` and it is proceessed event now but it's mark event as completed even it's not.

`2021-12-23 14:05:00,524 DEBUG tor$SharedEntityManagerInvocationHandler: 302 - Creating new EntityManager for shared EntityManager invocation
2021-12-23 14:05:00,570 DEBUG .jdbc.datasource.DriverManagerDataSource: 144 - Creating new JDBC DriverManager Connection to [jdbc:postgresql://localhost:5432/test_db]
2021-12-23 14:05:00,788 DEBUG r$CompletionRegisteringMethodInterceptor: 161 - Invocation of listener public void example.events.PersistentDomainEventIntegrationTest$SecondTxEventListener.on(example.events.PersistentDomainEventIntegrationTest$DomainEvent) failed. Leaving event publication uncompleted.
java.lang.IllegalStateException: null
	at example.events.PersistentDomainEventIntegrationTest$SecondTxEventListener.on(PersistentDomainEventIntegrationTest.java:144)
	at example.events.PersistentDomainEventIntegrationTest$SecondTxEventListener$$FastClassBySpringCGLIB$$fbc5212a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.moduliths.events.support.CompletionRegisteringBeanPostProcessor$CompletionRegisteringMethodInterceptor.invoke(CompletionRegisteringBeanPostProcessor.java:153)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at example.events.PersistentDomainEventIntegrationTest$SecondTxEventListener$$EnhancerBySpringCGLIB$$65faf98d.on(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229)
	at org.springframework.transaction.event.TransactionalApplicationListenerMethodAdapter.onApplicationEvent(TransactionalApplicationListenerMethodAdapter.java:99)
	at org.moduliths.events.support.PersistentApplicationEventMulticaster.executeListenerWithCompletion(PersistentApplicationEventMulticaster.java:131)
	at org.moduliths.events.support.PersistentApplicationEventMulticaster.lambda$invokeTargetListener$1(PersistentApplicationEventMulticaster.java:118)
	at java.base/java.util.Optional.map(Optional.java:258)
	at org.moduliths.events.support.PersistentApplicationEventMulticaster.invokeTargetListener(PersistentApplicationEventMulticaster.java:118)
	at org.moduliths.events.support.PersistentApplicationEventMulticaster.afterSingletonsInstantiated(PersistentApplicationEventMulticaster.java:106)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:963)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at example.events.PersistentDomainEventIntegrationTest.exposesEventPublicationForFailedListener(PersistentDomainEventIntegrationTest.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
2021-12-23 14:05:00,793 DEBUG tor$SharedEntityManagerInvocationHandler: 302 - Creating new EntityManager for shared EntityManager invocation
2021-12-23 14:05:00,823 DEBUG .jdbc.datasource.DriverManagerDataSource: 144 - Creating new JDBC DriverManager Connection to [jdbc:postgresql://localhost:5432/test_db]
2021-12-23 14:05:00,855 DEBUG s.events.jpa.JpaEventPublicationRegistry: 130 - Marking publication of event class example.events.PersistentDomainEventIntegrationTest$DomainEvent with id 438126f5-938b-4ce0-bbfe-0a9ef8f9109c to listener example.events.PersistentDomainEventIntegrationTest$SecondTxEventListener.on(example.events.PersistentDomainEventIntegrationTest$DomainEvent) completed.`

**Comment by oalbader** [comment]
I think this line of code `registry.get().markCompleted(publication);` is not necessarily since the completion will be marked if the event succeed in CompletionRegisteringMethodInterceptor

**Comment by oalbader** [comment]
We are planning to use it in production next week so we are appreciate it if you release it quickly. thanks a lot

**Comment by odrotbohm** [comment]
Alright, I'll make sure 1.2.2 goes out later today.

**Comment by oalbader** [comment]
yes, sure
